[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_18']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction'
]

[phases.build]
cmds = [
    'php artisan config:clear',
    'php artisan cache:clear',
    'chmod -R 777 storage bootstrap/cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port='
